name: Publish Docs Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy-docs:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - name: Setup
        working-directory: ./docs
        run: npm i -g @antfu/ni

      - name: Install
        working-directory: ./docs
        run: nci

      - name: Generate
        working-directory: ./docs
        run: nr generate

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     folder: docs/.output/public

      - name: Deploy to Vercel
        working-directory: ./docs
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
 